CHARITY_POOL = [
  {
    "ein": "13-1234567",
    "name": "Community Health Access",
    "url": "https://example.org/community-health",
    "summary": "Expands primary care clinics for low-income families across Midwest cities.",
    "location": "Chicago, IL",
    "issue_family": "health",
    "impact_modes": ["direct", "advocacy"],
    "geographies": ["local", "national"],
    "topics": ["healthcare", "equity", "youth"],
    "ntee": "E70",
  },
  {
    "ein": "95-9876543",
    "name": "Clean Air Initiative",
    "url": "https://example.org/clean-air",
    "summary": "Supports community monitors and litigation to cut air pollution in port cities.",
    "location": "Long Beach, CA",
    "issue_family": "environment",
    "impact_modes": ["advocacy", "research"],
    "geographies": ["local", "national"],
    "topics": ["climate", "equity"],
    "ntee": "C32",
  },
  {
    "ein": "11-2222333",
    "name": "Bright Futures Education Fund",
    "url": "https://example.org/bright-futures",
    "summary": "Scholarships and mentorship for first-generation college students.",
    "location": "Atlanta, GA",
    "issue_family": "education",
    "impact_modes": ["direct"],
    "geographies": ["national"],
    "topics": ["equity", "youth"],
    "ntee": "B82",
  },
  {
    "ein": "21-7654321",
    "name": "Global Clean Water Lab",
    "url": "https://example.org/global-water",
    "summary": "Researches low-cost filtration and deploys pilots with local partners.",
    "location": "Kampala, Uganda",
    "issue_family": "international",
    "impact_modes": ["research", "direct"],
    "geographies": ["global"],
    "topics": ["healthcare", "climate"],
    "ntee": "Q35",
  },
  {
    "ein": "31-4444555",
    "name": "River Guardians",
    "url": "https://example.org/river-guardians",
    "summary": "Restores wetlands and builds resilience to flooding along the Mississippi River.",
    "location": "St. Louis, MO",
    "issue_family": "environment",
    "impact_modes": ["direct", "research"],
    "geographies": ["local", "national"],
    "topics": ["climate", "water"],
    "ntee": "C34",
  },
  {
    "ein": "41-5555666",
    "name": "Arts Access Collective",
    "url": "https://example.org/arts-access",
    "summary": "Brings arts education to Title I schools with touring teaching artists.",
    "location": "Philadelphia, PA",
    "issue_family": "arts",
    "impact_modes": ["direct"],
    "geographies": ["local", "national"],
    "topics": ["arts", "youth"],
    "ntee": "A25",
  },
  {
    "ein": "52-6666777",
    "name": "Resilient Food Systems",
    "url": "https://example.org/resilient-food",
    "summary": "Invests in farmer co-ops to strengthen regional food security.",
    "location": "Des Moines, IA",
    "issue_family": "human_services",
    "impact_modes": ["direct", "advocacy"],
    "geographies": ["national"],
    "topics": ["food", "equity"],
    "ntee": "K30",
  },
  {
    "ein": "62-7777888",
    "name": "Wildlife Corridors Alliance",
    "url": "https://example.org/wildlife-corridors",
    "summary": "Secures protected pathways for endangered species across North America.",
    "location": "Bozeman, MT",
    "issue_family": "animals",
    "impact_modes": ["advocacy", "research"],
    "geographies": ["national", "global"],
    "topics": ["animals", "climate"],
    "ntee": "D30",
  },
  {
    "ein": "72-8888999",
    "name": "Civic Data Lab",
    "url": "https://example.org/civic-data",
    "summary": "Open-data advocacy that helps cities publish equity dashboards.",
    "location": "Austin, TX",
    "issue_family": "human_services",
    "impact_modes": ["advocacy", "research"],
    "geographies": ["national"],
    "topics": ["equity", "research"],
    "ntee": "W70",
  },
  {
    "ein": "82-9999000",
    "name": "City Arts Studio",
    "url": "https://example.org/city-arts",
    "summary": "Community art hubs that keep youth safe after school.",
    "location": "Oakland, CA",
    "issue_family": "arts",
    "impact_modes": ["direct"],
    "geographies": ["local"],
    "topics": ["arts", "youth", "equity"],
    "ntee": "A20",
  },
  {
    "ein": "92-1010101",
    "name": "STEM for All",
    "url": "https://example.org/stem-for-all",
    "summary": "After-school robotics and maker clubs in rural districts.",
    "location": "Billings, MT",
    "issue_family": "education",
    "impact_modes": ["direct"],
    "geographies": ["local", "national"],
    "topics": ["youth", "technology"],
    "ntee": "B84",
  },
  {
    "ein": "12-2020202",
    "name": "Climate Policy Accelerator",
    "url": "https://example.org/climate-policy",
    "summary": "Helps states design data-backed climate legislation.",
    "location": "Boston, MA",
    "issue_family": "environment",
    "impact_modes": ["advocacy", "research"],
    "geographies": ["national", "global"],
    "topics": ["climate", "policy"],
    "ntee": "C01",
  },
  {
    "ein": "23-3030303",
    "name": "Global Crisis Response",
    "url": "https://example.org/crisis-response",
    "summary": "Rapid relief funding for disasters with local-led accountability.",
    "location": "Manila, Philippines",
    "issue_family": "international",
    "impact_modes": ["direct"],
    "geographies": ["global"],
    "topics": ["humanitarian", "healthcare"],
    "ntee": "M20",
  }
]
